# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  project     = "tcinc-dev"
  region      = "northamerica-northeast2"
  zone        = "northamerica-northeast2-a"
  impersonate_service_account = "tc-tekstack-kps-priv-gke-sa@tcinc-dev.iam.gserviceaccount.com"
}

provider "google-beta" {
  project     = "tcinc-dev"
  region      = "northamerica-northeast2"
  zone        = "northamerica-northeast2-a"
  impersonate_service_account = "tc-tekstack-kps-priv-gke-sa@tcinc-dev.iam.gserviceaccount.com"
}

provider "helm" {
  kubernetes {
    host  = "https://${data.google_container_cluster.cluster.private_cluster_config[0].private_endpoint}"
    token = data.google_service_account_access_token.default.access_token
    cluster_ca_certificate = base64decode(
      data.google_container_cluster.cluster.master_auth[0].cluster_ca_certificate,
    )
  }
}

provider "kubernetes" {
  host  = "https://${data.google_container_cluster.cluster.private_cluster_config[0].private_endpoint}"
  token = data.google_service_account_access_token.default.access_token
  cluster_ca_certificate = base64decode(
    data.google_container_cluster.cluster.master_auth[0].cluster_ca_certificate,
  )
}
