# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket                      = "tc-tekstack-kps-terraform-state-bucket"
    impersonate_service_account = "tc-tekstack-kps-priv-gke-sa@tcinc-dev.iam.gserviceaccount.com"
    prefix                      = "gke/security/external_secrets/management/prod"
  }
}
